# Generated by Django 3.2.9 on 2021-12-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('fecha_baja', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cosecha', models.DateField()),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('codigo', models.BigIntegerField()),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='catalogo/')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cavovich.bodega')),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cavovich.estante')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cavovich.origen')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cavovich.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojo', models.PositiveSmallIntegerField(max_length=10)),
                ('nariz', models.PositiveSmallIntegerField(max_length=10)),
                ('boca', models.PositiveSmallIntegerField(max_length=10)),
                ('equilibrio_armonia', models.PositiveSmallIntegerField(max_length=10)),
                ('nota', models.TextField()),
                ('vino', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Cavovich.vino')),
            ],
        ),
    ]
