# Generated by Django 3.2.9 on 2021-12-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cavovich', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='boca',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='equilibrio_armonia',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nariz',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='ojo',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
