# Generated by Django 3.2.9 on 2021-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cavovich', '0002_auto_20211213_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='catalogo/'),
        ),
        migrations.AlterField(
            model_name='vino',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
