# Generated by Django 3.2.9 on 2021-12-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cavovich', '0003_auto_20211213_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='vino',
            name='imagen',
            field=models.ImageField(default='catalogo/default.png', upload_to='catalogo/'),
        ),
    ]
