# Generated by Django 3.2.9 on 2021-12-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cavovich', '0004_auto_20211216_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='cosecha',
            field=models.PositiveSmallIntegerField(max_length=2030),
        ),
    ]
