# Generated by Django 3.2.9 on 2021-12-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cavovich', '0005_alter_vino_cosecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='cosecha',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
